### ISSUE TITLE
Is this package supported in Jupyter notebooks?

### ISSUE THREAD

**Issue by GaurangTandon** [amosjyng/langchain-visualizer#19]
I didn't see any examples for Jupyter notebooks. Also, I got an error trying to use this package in a Jupyter notebook:

```
usage: ipykernel_launcher.py [-h]
                             [--mode {human,augmented,augmented-cached,machine,fake,test,approval,machine-cached}]
                             [--trace | --no-trace] [--version]
ipykernel_launcher.py: error: unrecognized arguments: --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"bbc7f181-2147-4e04-9da0-133c6a413dab" --shell=9002 --transport="tcp" --iopub=9004 --f=<path-to-log-json>
```

So I wanted to ask if the Jupyter notebooks are supported or not? Thanks!

**Comment by amosjyng** [comment]
Ah, it's not supported at the moment because I've never tried it in Jupyter -- but I've been meaning to fix that specific error as well, so let me see if fixing it helps

**Comment by sundar7D0** [comment]
Also, support for google colab will be nice!

**Comment by sundar7D0** [comment]
Any updates on support for colab/jupyter notebooks? It will be very helpful for debug!

**Comment by amosjyng** [comment]
Ah crap sorry, I've been working on other things at the moment, but I'll try to get to this next week! :)

**Comment by gbhall** [comment]
Ah bugger, just tried to use it, same issue! Can we please get a fix 🙏

I think most of us are using notebooks to learn and debug, and this tool would nicely compliment that, they go hand in hand together.

**Comment by gbhall** [comment]
```
usage: ipykernel_launcher.py [-h]
                             [--mode {human,augmented,augmented-cached,machine,fake,test,approval,machine-cached}]
                             [--trace | --no-trace] [--version]
ipykernel_launcher.py: error: unrecognized arguments: -f /Users/gbhall/Library/Jupyter/runtime/kernel-c3cf09d2-1550-4982-befb-c0a6823e200f.json
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
/opt/homebrew/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3468: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
```

**Comment by amosjyng** [comment]
Thanks for your patience everyone! I've just released `v0.0.18` that works on Jupyter notebook. You can see [a demo notebook here](https://github.com/amosjyng/langchain-visualizer/blob/v0.0.18/tests/demo.ipynb) (the actual visualization won't show up until you run it yourself because it relies on metadata saved locally on your computer).

`v0.0.18` of langchain-visualizer depends on `v0.0.125` of langchain, so please update accordingly.

I'll close this issue for now, but please let me know if you have any issues :)

**Comment by amosjyng** [comment]
I'm guessing most likely not, as it spins up a server locally and then connects to that local webpage on Jupyter

**Comment by sundar7D0** [comment]
Yeah! It doesn't work with google colab unfortunately. It would be a great feature as many people work on colab for their AI prototypes!

**Comment by amosjyng** [comment]
Understandable, unfortunately that would require a major effort as the underlying package (ICE) currently does not support that :(
