### ISSUE TITLE
TimeoutError: Server didn't start within 10 seconds

### ISSUE THREAD

**Issue by lironezra** [amosjyng/langchain-visualizer#40]
Hi :)

I'm encountering an error message when I ask my chatbot every questions. Is there an option to increase the timeout or is there another solution available?

Thanks!

**Comment by amosjyng** [comment]
Hey there! :)

What environment are you running this in?

Could you try using the latest version, 0.0.24, to see if there's any command output being logged? You should now see something like `ICE server failed to start. Command output:`

To increase the timeout, you can now do

```python
import langchain_visualizer
langchain_visualizer.ice.server.ICE_WAIT_TIME = 2
```

But I think it's unlikely that the time to start up the visualization server is the issue here :P

**Comment by lironezra** [comment]
Hey @amosjyng 

Thank you for your reply. I upgraded the package, but I'm still encountering this error. Could you clarify what you mean by 'the environment I am using'? I also tried to run the example from the documentation, but it isn't working either.

**Comment by amosjyng** [comment]
Ah yeah, unfortunately the update was mostly just to provide better debug info, so it wouldn't really change anything else about how it runs.

Do you now see a line in the log output that says

> ICE server failed to start. Command output:

If so, what output do you see from the command?

By "environment," I meant what OS are you running this on? And are you running it in Jupyter?

**Comment by lironezra** [comment]
So regarding the environment it's Windows, I didn't get this message like you said and I don't using Jupyter.
When I starts the program this is what I got: (When I click on the URL it takes me to unreachable site)
![image](https://github.com/amosjyng/langchain-visualizer/assets/28096499/0944197d-ae27-43c6-a1b5-8b7466d09f09)

and after few seconds I got this Exception:
![image](https://github.com/amosjyng/langchain-visualizer/assets/28096499/cd818024-23e4-45d5-96a2-df95bf197759)

Hope it will help you to understand my problem :)
Thanks!

**Comment by amosjyng** [comment]
Oh interesting! Thanks, I'll try to reproduce it.

In the meantime, can you see what happens when you run the following command?

```bash
python -m ice.server stop
```

**Comment by amosjyng** [comment]
Hey @lironezra @biwa7636 , sorry for the wait! I finally reproduced the problem on Windows and I think I've fixed it. Can you please check the latest version 0.0.25?

Thanks!
