### ISSUE TITLE
AttributeError: type object 'OpenAIEmbeddings' has no attribute '_embedding_func'

### ISSUE THREAD

**Issue by mkamalov** [amosjyng/langchain-visualizer#77]
I have the following error on 0.0.29 version:

AttributeError: type object 'OpenAIEmbeddings' has no attribute '_embedding_func'

Please, could you help me?

**Comment by mkamalov** [comment]
I investigated the problem in version Langchain 0.0.250 the method '_embedding_func' has been removed.

**Comment by amosjyng** [comment]
Hey, thank you for letting me know! I have just released v0.0.30, which uses the latest version of langchain. Please let me know if you still have any issues :)
