### ISSUE TITLE
After migration to langchain=0.0.341 and openai=1.3.5 stop working

### ISSUE THREAD

**Issue by mkamalov** [amosjyng/langchain-visualizer#83]
I migrated langchain to 0.0.341 and openai 1.3.5 to have an access to gpt-4-1106-preview.

After migration langchain-visualizer to 0.0.31 stopped working and no error in the console.

Please, could you look at the issue?

**Comment by mkamalov** [comment]
<img width="623" alt="image" src="https://github.com/amosjyng/langchain-visualizer/assets/6793308/50521a7e-d789-4088-a0f1-7072878672fa">

**Comment by mkamalov** [comment]
<img width="555" alt="image" src="https://github.com/amosjyng/langchain-visualizer/assets/6793308/c11ded5d-90c1-45c2-a881-96f8f97fc137">
Seems 0.0.31 is outdated for langchain 0.0.341

**Comment by amosjyng** [comment]
Hey @mkamalov , sorry for the wait! #84 (released with v0.0.32) should make it compatible with the latest langchain now. Let me know if it still doesn't work.
